<script setup>
import { computed, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessageBox } from 'element-plus'
import { clearToken } from '@/utils/session'

const route=useRoute(),router=useRouter();const collapsed=ref(false);const mobileOpen=ref(false)
const menus=[['/dashboard','DataBoard','工作台'],['/movies','Film','影片'],['/articles','Document','文章'],['/courses','Reading','课程'],['/paths','Guide','学习路径'],['/tools','MagicStick','AI 工具'],['/subscribers','Message','订阅用户']]
const title=computed(()=>route.meta.title||'管理后台')
async function logout(){await ElMessageBox.confirm('确定退出当前管理会话？','退出登录',{type:'warning'});clearToken();router.replace('/login')}
</script>
<template><div class="admin-shell"><aside class="sidebar" :class="{collapsed,open:mobileOpen}"><div class="sidebar-brand"><span>CV</span><div v-if="!collapsed"><strong>CineVerse</strong><small>ADMIN CONSOLE</small></div></div><el-menu :default-active="route.path" router :collapse="collapsed" background-color="transparent" text-color="#9ca3af" active-text-color="#f0c873"><el-menu-item v-for="item in menus" :key="item[0]" :index="item[0]" @click="mobileOpen=false"><el-icon><component :is="item[1]"/></el-icon><template #title>{{item[2]}}</template></el-menu-item></el-menu><div class="sidebar-foot"><button @click="collapsed=!collapsed"><el-icon><Fold v-if="!collapsed"/><Expand v-else/></el-icon><span v-if="!collapsed">收起导航</span></button></div></aside><div v-if="mobileOpen" class="overlay" @click="mobileOpen=false"></div><section class="workspace"><header><div><button class="mobile-menu" aria-label="打开导航" @click="mobileOpen=true"><el-icon><Menu/></el-icon></button><span class="crumb">内容管理 /</span><strong>{{title}}</strong></div><div class="header-actions"><a href="http://127.0.0.1:4173" target="_blank" rel="noopener noreferrer">查看前台 <el-icon><TopRight/></el-icon></a><el-dropdown><button class="admin-user" aria-label="管理员菜单"><span>A</span><div><strong>内容管理员</strong><small>Administrator</small></div><el-icon><ArrowDown/></el-icon></button><template #dropdown><el-dropdown-menu><el-dropdown-item @click="logout">退出登录</el-dropdown-item></el-dropdown-menu></template></el-dropdown></div></header><main><router-view :key="route.fullPath"/></main></section></div></template>
<style scoped>.admin-shell{min-height:100vh;display:flex}.sidebar{position:fixed;inset:0 auto 0 0;z-index:30;width:230px;display:flex;flex-direction:column;background:var(--admin-navy);transition:.22s ease}.sidebar.collapsed{width:72px}.sidebar-brand{height:74px;display:flex;align-items:center;gap:12px;padding:0 19px;border-bottom:1px solid rgba(255,255,255,.07);color:white}.sidebar-brand>span{width:34px;height:34px;display:grid;place-items:center;flex:none;border:1px solid #c99845;border-radius:50%;color:#e6c276;font:700 11px Georgia}.sidebar-brand div{display:grid}.sidebar-brand strong{font:600 16px Georgia}.sidebar-brand small{margin-top:3px;color:#687386;font-size:8px;letter-spacing:.14em}.el-menu{flex:1;padding:20px 10px;border:0}.el-menu-item{height:46px;margin:3px 0;border-radius:8px}.el-menu-item.is-active{background:rgba(201,152,69,.13)!important}.sidebar-foot{padding:15px;border-top:1px solid rgba(255,255,255,.07)}.sidebar-foot button{width:100%;display:flex;align-items:center;gap:12px;padding:10px;border:0;background:none;color:#798293;cursor:pointer}.workspace{width:calc(100% - 230px);min-height:100vh;margin-left:230px;transition:.22s ease}.sidebar.collapsed+.workspace{width:calc(100% - 72px);margin-left:72px}.workspace>header{height:74px;display:flex;align-items:center;justify-content:space-between;padding:0 30px;border-bottom:1px solid #e7eaf0;background:white}.workspace>header>div{display:flex;align-items:center;gap:8px}.crumb{color:#98a2b3;font-size:12px}.header-actions>a{display:flex;align-items:center;gap:4px;color:#667085;font-size:12px;text-decoration:none}.admin-user{display:flex;align-items:center;gap:10px;margin-left:15px;padding:6px;border:0;background:none;cursor:pointer}.admin-user>span{width:34px;height:34px;display:grid;place-items:center;border-radius:50%;background:#f3e8d1;color:#9a6a22;font-weight:700}.admin-user div{display:grid;text-align:left}.admin-user strong{font-size:12px}.admin-user small{color:#98a2b3;font-size:10px}.workspace main{padding:30px}.mobile-menu{display:none;border:0;background:none}.overlay{display:none}@media(max-width:800px){.sidebar{transform:translateX(-100%)}.sidebar.open{width:230px;transform:none}.workspace,.sidebar.collapsed+.workspace{width:100%;margin-left:0}.mobile-menu{display:inline-grid;place-items:center}.crumb{display:none}.workspace>header{padding:0 18px}.workspace main{padding:22px 16px}.overlay{position:fixed;inset:0;z-index:20;display:block;background:rgba(17,24,39,.45)}.header-actions>a,.admin-user div{display:none}}</style>
