export const resourceConfigs = {
  movies: {
    singular: '影片',
    description: '维护影片档案、评分与首页推荐状态',
    searchPlaceholder: '搜索片名、导演或类型',
    defaults: { year: new Date().getFullYear(), rating: 0, duration: 0, isFeatured: false, posterColor: '#273449', posterIcon: '🎬' },
    fields: [
      { key: 'title', label: '中文片名', required: true },
      { key: 'originalTitle', label: '原始片名' },
      { key: 'year', label: '年份', type: 'number', min: 1888, max: 2200 },
      { key: 'genres', label: '类型', placeholder: '剧情 / 科幻' },
      { key: 'rating', label: '评分', type: 'number', min: 0, max: 10, step: 0.1 },
      { key: 'director', label: '导演' },
      { key: 'duration', label: '片长（分钟）', type: 'number', min: 0 },
      { key: 'posterIcon', label: '海报符号', placeholder: '🎬' },
      { key: 'posterColor', label: '主题颜色', type: 'color' },
      { key: 'description', label: '影片简介', type: 'textarea', span: 2, rows: 4 },
      { key: 'isFeatured', label: '首页推荐', type: 'switch' },
    ],
    columns: [
      { key: 'title', label: '片名', minWidth: 190, primary: true },
      { key: 'year', label: '年份', width: 82 },
      { key: 'genres', label: '类型', minWidth: 130, tag: true },
      { key: 'rating', label: '评分', width: 84, rating: true },
      { key: 'director', label: '导演', minWidth: 110 },
      { key: 'isFeatured', label: '推荐', width: 80, boolean: true },
    ],
  },
  articles: {
    singular: '文章',
    description: '编辑影评、学习笔记和 AI 专栏内容',
    searchPlaceholder: '搜索标题、作者、分类或标签',
    defaults: { category: 'movie-review', author: '一格', viewCount: 0, coverColor: '#28364a', publishedAt: new Date().toISOString() },
    fields: [
      { key: 'title', label: '文章标题', required: true, span: 2 },
      { key: 'category', label: '内容分类', type: 'select', required: true, options: [['movie-review', '电影评论'], ['learning-note', '学习笔记'], ['ai-article', 'AI 专栏']] },
      { key: 'tag', label: '内容标签', placeholder: '深度影评' },
      { key: 'author', label: '作者' },
      { key: 'publishedAt', label: '发布时间', type: 'datetime' },
      { key: 'coverColor', label: '封面颜色', type: 'color' },
      { key: 'viewCount', label: '阅读量', type: 'number', min: 0 },
      { key: 'summary', label: '内容摘要', type: 'textarea', span: 2, rows: 3 },
      { key: 'content', label: '正文', type: 'textarea', span: 2, rows: 10 },
    ],
    columns: [
      { key: 'title', label: '标题', minWidth: 230, primary: true },
      { key: 'category', label: '分类', width: 110, category: true },
      { key: 'tag', label: '标签', width: 110, tag: true },
      { key: 'author', label: '作者', width: 90 },
      { key: 'viewCount', label: '阅读', width: 80 },
      { key: 'publishedAt', label: '发布时间', width: 150, date: true },
    ],
  },
  courses: {
    singular: '课程',
    description: '编排学习内容、难度与课时信息',
    searchPlaceholder: '搜索课程、分类或难度',
    defaults: { level: '入门', lessons: 1, isActive: true, icon: '📚' },
    fields: [
      { key: 'title', label: '课程名称', required: true, span: 2 },
      { key: 'category', label: '课程分类', placeholder: '电影 / AI' },
      { key: 'level', label: '难度', type: 'select', options: [['入门', '入门'], ['进阶', '进阶'], ['高级', '高级']] },
      { key: 'duration', label: '预计时长', placeholder: '4 周' },
      { key: 'lessons', label: '课时数', type: 'number', min: 0 },
      { key: 'icon', label: '课程符号', placeholder: '📚' },
      { key: 'isActive', label: '对外展示', type: 'switch' },
      { key: 'description', label: '课程简介', type: 'textarea', span: 2, rows: 5 },
    ],
    columns: [
      { key: 'title', label: '课程', minWidth: 220, primary: true },
      { key: 'category', label: '分类', width: 110, tag: true },
      { key: 'level', label: '难度', width: 90 },
      { key: 'duration', label: '时长', width: 100 },
      { key: 'lessons', label: '课时', width: 80 },
      { key: 'isActive', label: '展示', width: 80, boolean: true },
    ],
  },
  paths: {
    singular: '学习路径',
    description: '组合课程，规划循序渐进的学习路线',
    searchPlaceholder: '搜索路径名称或描述',
    defaults: {},
    fields: [
      { key: 'name', label: '路径名称', required: true, span: 2 },
      { key: 'courseIds', label: '课程 ID', span: 2, placeholder: '按顺序填写，例如：1,2,5' },
      { key: 'description', label: '路径说明', type: 'textarea', span: 2, rows: 6 },
    ],
    columns: [
      { key: 'name', label: '路径名称', minWidth: 210, primary: true },
      { key: 'description', label: '说明', minWidth: 300, ellipsis: true },
      { key: 'courseIds', label: '课程 ID', minWidth: 150, tag: true },
    ],
  },
  tools: {
    singular: 'AI 工具',
    description: '维护创作工具、标签和访问入口',
    searchPlaceholder: '搜索工具、分类或标签',
    defaults: { isFree: true, featured: false, icon: '✨' },
    fields: [
      { key: 'name', label: '工具名称', required: true },
      { key: 'category', label: '分类', placeholder: '视频 / 写作 / 图像' },
      { key: 'url', label: '访问地址', span: 2, placeholder: 'https://example.com' },
      { key: 'icon', label: '工具符号', placeholder: '✨' },
      { key: 'tags', label: '标签', placeholder: '生成式 AI / 免费' },
      { key: 'isFree', label: '可免费使用', type: 'switch' },
      { key: 'featured', label: '重点推荐', type: 'switch' },
      { key: 'description', label: '工具简介', type: 'textarea', span: 2, rows: 5 },
    ],
    columns: [
      { key: 'name', label: '工具', minWidth: 180, primary: true },
      { key: 'category', label: '分类', width: 110, tag: true },
      { key: 'tags', label: '标签', minWidth: 150 },
      { key: 'isFree', label: '免费', width: 80, boolean: true },
      { key: 'featured', label: '推荐', width: 80, boolean: true },
      { key: 'url', label: '访问地址', minWidth: 170, link: true },
    ],
  },
}

export const categoryNames = {
  'movie-review': '电影评论',
  'learning-note': '学习笔记',
  'ai-article': 'AI 专栏',
}
