<script setup>
import { computed, onMounted, ref } from 'vue'
import { dashboardApi } from '@/api'
import { ElMessage } from 'element-plus'
const loading=ref(true);const data=ref({counts:{},recentArticles:[],recentMovies:[]})
const cards=computed(()=>[['movies','Film','影片内容','#b98535'],['articles','Document','文章笔记','#5470c6'],['courses','Reading','学习课程','#3ba272'],['tools','MagicStick','AI 工具','#9a60b4'],['subscribers','Message','订阅用户','#d87c7c'],['paths','Guide','学习路径','#6f7785']])
async function load(){try{data.value=(await dashboardApi.get()).data}catch(e){ElMessage.error(e.message)}finally{loading.value=false}}onMounted(load)
</script>
<template><div v-loading="loading"><div class="page-head"><div><h1>编辑工作台</h1><p>今天也一起把内容整理得更好。</p></div><el-button type="primary" icon="Plus" @click="$router.push('/articles')">撰写文章</el-button></div><section class="metric-grid"><article v-for="card in cards" :key="card[0]" class="metric panel"><div :style="{background:card[3]+'18',color:card[3]}"><el-icon><component :is="card[1]"/></el-icon></div><span><small>{{card[2]}}</small><strong>{{data.counts[card[0]]||0}}</strong></span></article></section><section class="dashboard-grid"><div class="panel recent"><div class="panel-head"><h2>最近更新的文章</h2><el-button link type="primary" @click="$router.push('/articles')">查看全部</el-button></div><el-table :data="data.recentArticles" empty-text="暂无文章"><el-table-column prop="title" label="标题" min-width="220"/><el-table-column prop="category" label="分类" width="110"/><el-table-column prop="author" label="作者" width="110"/><el-table-column label="更新时间" width="170"><template #default="scope">{{new Date(scope.row.updatedAt).toLocaleString('zh-CN')}}</template></el-table-column></el-table></div><div class="panel shortcuts"><div class="panel-head"><h2>快速开始</h2></div><button @click="$router.push('/movies')"><el-icon><Film/></el-icon><span><strong>添加一部影片</strong><small>完善片库与编辑推荐</small></span><el-icon><ArrowRight/></el-icon></button><button @click="$router.push('/courses')"><el-icon><Reading/></el-icon><span><strong>维护学习内容</strong><small>更新课程和学习路径</small></span><el-icon><ArrowRight/></el-icon></button><button @click="$router.push('/tools')"><el-icon><MagicStick/></el-icon><span><strong>收录 AI 工具</strong><small>管理推荐与外部链接</small></span><el-icon><ArrowRight/></el-icon></button></div></section></div></template>
<style scoped>.metric-grid{display:grid;grid-template-columns:repeat(6,1fr);gap:15px;margin-bottom:24px}.metric{display:flex;align-items:center;gap:13px;padding:20px}.metric>div{width:42px;height:42px;display:grid;place-items:center;border-radius:10px;font-size:20px}.metric>span{display:grid}.metric small{color:var(--admin-muted);font-size:11px}.metric strong{margin-top:3px;font-size:24px}.dashboard-grid{display:grid;grid-template-columns:minmax(0,1.6fr) minmax(280px,.7fr);gap:20px}.panel-head{height:62px;display:flex;align-items:center;justify-content:space-between;padding:0 20px;border-bottom:1px solid #edf0f4}.panel-head h2{font-size:15px}.recent{overflow:hidden}.shortcuts{overflow:hidden}.shortcuts button{width:100%;display:grid;grid-template-columns:38px 1fr auto;align-items:center;gap:12px;padding:18px 20px;border:0;border-bottom:1px solid #edf0f4;background:white;text-align:left;cursor:pointer}.shortcuts button:hover{background:#faf9f6}.shortcuts button>svg,.shortcuts button>.el-icon:first-child{color:#b98535;font-size:18px}.shortcuts span{display:grid;gap:4px}.shortcuts small{color:#98a2b3}@media(max-width:1200px){.metric-grid{grid-template-columns:repeat(3,1fr)}}@media(max-width:850px){.dashboard-grid{grid-template-columns:1fr}}@media(max-width:560px){.metric-grid{grid-template-columns:repeat(2,1fr)}.metric{padding:15px}}</style>
