<script setup>
import { reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import { authApi } from '@/api'
import { setToken } from '@/utils/session'

const router=useRouter(),route=useRoute();const loading=ref(false);const form=reactive({username:'admin',password:''})
async function submit(){if(!form.username||!form.password){ElMessage.warning('请输入账号和密码');return}loading.value=true;try{const response=await authApi.login(form);setToken(response.data.token);ElMessage.success('欢迎回来');router.replace(String(route.query.redirect||'/dashboard'))}catch(error){ElMessage.error(error.message)}finally{loading.value=false}}
</script>
<template><main class="login-page"><section class="login-brand"><div class="brand-mark">CV</div><span>CONTENT OPERATIONS</span><h1>让每一份内容，<br/>都有清晰的归处。</h1><p>管理影片、文章、课程与创作工具。所有修改都会同步进入 CineVerse 的内容数据库。</p><div class="brand-footer">CINEVERSE · EDITORIAL CONSOLE</div></section><section class="login-panel"><div class="login-card"><small>SECURE ACCESS</small><h2>登录管理后台</h2><p>使用管理员凭据继续</p><el-form size="large" @submit.prevent="submit"><el-form-item><el-input v-model="form.username" prefix-icon="User" placeholder="管理员账号" autocomplete="username"/></el-form-item><el-form-item><el-input v-model="form.password" prefix-icon="Lock" placeholder="密码" type="password" show-password autocomplete="current-password" @keyup.enter="submit"/></el-form-item><el-button type="primary" :loading="loading" class="login-button" @click="submit">进入工作台</el-button></el-form><div class="security-note"><el-icon><Lock/></el-icon>会话仅保存在当前浏览器标签页</div></div></section></main></template>
<style scoped>.login-page{min-height:100vh;display:grid;grid-template-columns:1.1fr .9fr;background:#f5f3ee}.login-brand{position:relative;display:flex;flex-direction:column;justify-content:center;padding:clamp(50px,8vw,120px);overflow:hidden;background:radial-gradient(circle at 80% 25%,rgba(201,152,69,.22),transparent 27%),linear-gradient(145deg,#111827,#090d14);color:#f7f3eb}.login-brand::after{position:absolute;right:-10%;bottom:-15%;width:450px;height:450px;border:1px solid rgba(201,152,69,.18);border-radius:50%;content:''}.brand-mark{width:52px;height:52px;display:grid;place-items:center;margin-bottom:55px;border:1px solid rgba(201,152,69,.6);border-radius:50%;color:#dcb86f;font-family:Georgia,serif}.login-brand>span,.login-card>small{color:#c99845;font-size:11px;font-weight:600;letter-spacing:.2em}.login-brand h1{max-width:700px;margin:20px 0 26px;font-family:var(--admin-sans);font-size:clamp(42px,5vw,68px);font-weight:500;line-height:1.24;letter-spacing:.015em}.login-brand p{max-width:520px;color:#b8c0cc;line-height:1.9}.brand-footer{position:absolute;bottom:35px;color:#8993a3;font-size:10px;letter-spacing:.16em}.login-panel{display:grid;place-items:center;padding:35px}.login-card{width:min(410px,100%)}.login-card h2{margin:14px 0 8px;font-size:28px;font-weight:600}.login-card>p{margin:0 0 32px;color:#6f7886}.login-button{width:100%;margin-top:5px}.security-note{display:flex;align-items:center;justify-content:center;gap:7px;margin-top:24px;color:#7f8998;font-size:12px}@media(max-width:800px){.login-page{grid-template-columns:1fr}.login-brand{min-height:320px;padding:55px 35px}.login-brand h1{font-size:40px}.brand-mark{margin-bottom:25px}.brand-footer{display:none}.login-panel{padding:60px 25px}}</style>
